package com.remodstudios.endless.client;

import com.remodstudios.endless.Endless;
import com.remodstudios.endless.block.EndlessModBlocks;
import com.remodstudios.endless.item.EndlessModItems;
import com.swordglowsblue.artifice.api.Artifice;
import net.fabricmc.api.ClientModInitializer;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;

import static com.remodstudios.endless.Endless.MOD_NAME;

public class EndlessClient implements ClientModInitializer {
	public static final Logger LOGGER = LogManager.getLogger(MOD_NAME + "|Client");

    @Override
    public void onInitializeClient() {
    	log(Level.INFO, "Initializing client");
		Artifice.registerAssetPack(Endless.id("generated_assets"), pack -> {
			pack.setDisplayName("Endless - Generated Assets");
			pack.setDescription("Resource pack generated by Endless");

			EndlessModItems.INSTANCE.generateAssets(pack);
			EndlessModBlocks.INSTANCE.generateAssets(pack);

			if (Boolean.getBoolean("com.remodstudios.endless.dump_artifice")) {
				try {
					pack.dumpResources("artifice.dbg", "assets");
				} catch (IOException ioe) {
					Endless.LOGGER.error("BRUH! Artifice failed to dump!");
					ioe.printStackTrace();
				}
			}
		});
	}

	public static void log(Level level, String message){
		LOGGER.log(level, "[" + MOD_NAME + "|Client] " + message);
	}
}
