package com.remodstudios.endless;

import com.remodstudios.endless.block.EndlessModBlocks;
import com.remodstudios.endless.block.entity.EndlessModBlockEntityTypes;
import com.remodstudios.endless.item.EndlessModItems;
import com.remodstudios.endless.world.feature.EndlessModFeatures;
import com.swordglowsblue.artifice.api.Artifice;
import net.minecraft.util.Identifier;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.fabricmc.api.ModInitializer;

import java.io.IOException;

public class Endless implements ModInitializer {
    public static final String MOD_ID = "endless";
    public static final String MOD_NAME = "Endless";
    public static final Logger LOGGER = LogManager.getLogger(MOD_NAME);

    @Override
    public void onInitialize() {
        log(Level.INFO, "Initializing");
        EndlessModItems.INSTANCE.init();
        EndlessModBlocks.INSTANCE.init();
		EndlessModBlockEntityTypes.init();
        EndlessModFeatures.init();

		Artifice.registerDataPack(id("generated_data"), pack -> {
			pack.setDisplayName("Endless - Generated Data");
			pack.setDescription("Data pack generated by Endless");

			EndlessModItems.INSTANCE.generateData(pack);
			EndlessModBlocks.INSTANCE.generateData(pack);

			if (Boolean.getBoolean("com.remodstudios.endless.dump_artifice")) {
				try {
					pack.dumpResources("artifice.dbg", "data");
				} catch (IOException ioe) {
					log(Level.ERROR, "BRUH! Artifice failed to dump!");
					ioe.printStackTrace();
				}
			}
		});
    }

    public static Identifier id(String path) { return new Identifier(MOD_ID, path); }

	public static void log(Level level, String message) {
    	LOGGER.log(level, "[" + MOD_NAME + "] " + message);
	}
}
